adjective1=(input("enter an adjective:"))
noun1= (input("enter an noun(place,thing,person):"))
adjective2= (input("enter another adjective:"))
verb1= (input("enter a verb in persent tense:"))
adjective3= (input("enter another adjective:"))
print(f"today i went to a {adjective1} zoo")
print(f"in an exhibit I saw a {noun1}!")
print(f"was {adjective2} and {verb1}")
print(f"I was {adjective3}")
