name=input("enter your name")
phone_number=(input("enter your phone number"))
result=len(name)
print(f"{result}")
result1=name.rfind("e")
print(f"{result1}")
result2=name.isdigit()
print(f"{result2}")
reult3=name.isalpha()
print(f"{reult3}")
result4=len(phone_number)
print(f"{result4}")